export const CELL_SELECTED_EVENT = 'CELL_SELECTED_EVENT';
export const NUMPAD_SELECTED_EVENT = 'NUMPAD_SELECTED_EVENT';
export const NEW_GAME_SELECTED_EVENT = 'NEW_GAME_SELECTED_EVENT';
export const DATA_TYPE = 'DATA_TYPE';
export const VIEW_TYPE = 'VIEW_TYPE';


